### ISSUE TITLE
Variable width

### ISSUE THREAD

**Issue by turnstep** [manvscode/timezoner#3]
Would be nice if the decision to truncate long fields (at the moment, for example, names over 30 bytes) would be configurable, as my terminal can handle a longer box :)

**Comment by manvscode** [comment]
@turnstep  This should be easy.  I'll look at this today.

**Comment by turnstep** [comment]
Heh - I already wrote some code. It was a little trickier than I thought
due to the truncation - we don't want to truncate at the start of a UTF-8
character! Will push something soonish.

**Comment by manvscode** [comment]
@turnstep Thanks.  I'm looking at your changes now.

**Comment by manvscode** [comment]
@turnstep Can you give my latest commits a try?  You can specify the column widths with the -T option.

./bin/timezoner -T 30 40


I noticed a few problems with names or emails that contain lots of UTF-8 characters.  If these changes are problematic then I think I need to do a larger code change and migrate to wide characters.

**Comment by turnstep** [comment]
Cool, the -T arguments seem to work just fine.
